ALTER TABLE sites
  ADD COLUMN IF NOT EXISTS protocol_version TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS capabilities JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS applied_revision TEXT NOT NULL DEFAULT '';
